# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170816_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
            preserve_default=False,
        ),
    ]
